# Generated by Django 3.2.9 on 2021-12-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_region_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
