# Generated by Django 3.2.9 on 2021-12-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='accomodation',
            new_name='accommodation',
        ),
    ]
