# Generated by Django 3.2.9 on 2021-12-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='score_1',
        ),
        migrations.AddField(
            model_name='accommodations',
            name='bathroom',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='accommodations',
            name='campus',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accommodations',
            name='catering',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accommodations',
            name='occupancy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='accommodations',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='accommodations',
            name='student_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='internet',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='overall',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='social',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='value_of_money',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
