# Generated by Django 3.2.9 on 2021-12-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20211231_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodations',
            name='bathroom',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accommodations',
            name='student_type',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
