# Generated by Django 3.2.9 on 2022-02-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_comment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodations',
            name='occupancy',
        ),
    ]
