# Generated by Django 3.2.9 on 2022-02-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_accommodations_occupancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodations',
            name='occupancy',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='accommodations',
            name='student_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
