# Generated by Django 4.0 on 2022-02-20 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_accommodations_image'),
        ('pages', '0015_delete_user_accommodations_post_code'),
    ]

    operations = [
    ]
