# Generated by Django 3.2.9 on 2022-02-22 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_merge_20220220_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(height_field=500, null=True, upload_to=None, width_field=800)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.accommodations')),
            ],
        ),
    ]
