# Generated by Django 4.0 on 2022-03-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_comment_location_comment_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
