# Generated by Django 3.2.9 on 2022-02-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_image_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_table',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
