# Generated by Django 4.0 on 2022-03-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_comment_subject'),
        ('pages', '0018_alter_question_answer'),
    ]

    operations = [
    ]
