# Generated by Django 4.0 on 2022-03-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_image_table_images'),
        ('pages', '0019_merge_20220309_1849'),
    ]

    operations = [
    ]
