# Generated by Django 4.0 on 2022-03-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_merge_20220309_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
