# Generated by Django 4.0 on 2022-03-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_merge_20220318_1459'),
        ('pages', '0021_alter_comment_subject_question'),
    ]

    operations = [
    ]
